name = "project-website-template"
license = "MIT"
description = ""
homepage = "https://github.com/Malthe57/project-website-template"
tags = []
features = []
min_version = "0.1.0"

[author]
  name = "Aorta Boys"
  homepage = "github.com/Malthe57"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
